"""Initial

Revision ID: 1c2f4ab292b9
Revises: None
Create Date: 2013-08-03 18:52:43.896000

"""

# revision identifiers, used by Alembic.
revision = '1c2f4ab292b9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
